title: My Notebook
author:
  name: Phuong Dao
  email: phuong018@gmail.com

description: >
  This is the place where I keep my small notes together.

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

minima:
  skin: classic